yandex:
  key: 80ac0d6d-c3bb-4b47-ae3f-7302308f1173

server:
  port: 8080

logging:
  level:
    ru.clevertec.weathertesttask: DEBUG

spring:
  data:
    mongodb:
      host: mongo_db
      database: weather_database
      port: 27017
  cloud:
    openfeign:
      client:
        config:
          weather:
            url: https://api.weather.yandex.ru/v2/forecast

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled:true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
