yandex:
  key: d86f2e3f-e85a-4abd-9d86-3cb87c3d159d

server:
  port: 8080

logging:
  level:
    ru.clevertec.weathertesttask: DEBUG

spring:
  data:
    mongodb:
      host: localhost
      database: weather_database
      port: 27017
  cloud:
    openfeign:
      client:
        config:
          weather:
            url: https://api.weather.yandex.ru/v2/forecast
