global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
#  - job_name: 'prometheus'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: [ 'host.docker.internal:9090' ]
  - job_name: 'docker'
    static_configs:
      - targets: [ "host.docker.internal:9323" ]
  - job_name: 'weather-app'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]